on:
  workflow_dispatch:
    inputs:
      version:
        description: "Nuget package version"
        required: true
        type: string
        default: '0.0.1-preview'

jobs:
  release:
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: pack
        run: dotnet pack ./src/TestFixture.sln -p:Configuration=Release -p:Version=${{ inputs.Version }} -o "./build"

      - name: push to nuget
        run: dotnet nuget push ./build/*.nupkg -k ${{ secrets.NUGET }} -s https://api.nuget.org/v3/index.json