on: push

jobs:
  verify:
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
          dotnet-quality: 'preview'

      - name: Test
        run: dotnet test ./src/TestFixture.Tests/TestFixture.Tests.csproj
