on: push

jobs:
  verify:
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            9.0.x
            10.0.x

      - name: Build
        run: dotnet build ./src/TestFixture.slnx

      - name: Test
        run: dotnet test --no-build --no-restore ./src/TestFixture.slnx

      - name: Format
        run: dotnet format --verify-no-changes --no-restore ./src/TestFixture.slnx
